version: '3.8'

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=loynis
      - DB_PASSWORD=loynis
      - DB_NAME=gymDB
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: gymDB
    environment:
      POSTGRES_DB: gymDB
      POSTGRES_USER: loynis
      POSTGRES_PASSWORD: loynis
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: