ALTER TABLE meals
  ADD COLUMN IF NOT EXISTS calories_per_100g FLOAT,
  ADD COLUMN IF NOT EXISTS protein_per_100g FLOAT,
  ADD COLUMN IF NOT EXISTS carbs_per_100g FLOAT,
  ADD COLUMN IF NOT EXISTS fats_per_100g FLOAT,
  ADD COLUMN IF NOT EXISTS vitamin_a_per_100g FLOAT,
  ADD COLUMN IF NOT EXISTS vitamin_c_per_100g FLOAT,
  ADD COLUMN IF NOT EXISTS calcium_per_100g FLOAT,
  ADD COLUMN IF NOT EXISTS magnesium_per_100g FLOAT,
  ADD COLUMN IF NOT EXISTS fiber_per_100g FLOAT,
  ADD COLUMN IF NOT EXISTS salt_per_100g FLOAT;