-- Add vitamins and minerals columns to diet table
ALTER TABLE diet
ADD COLUMN IF NOT EXISTS vitamin_a_min INTEGER DEFAULT 700,
ADD COLUMN IF NOT EXISTS vitamin_a_max INTEGER DEFAULT 900,
ADD COLUMN IF NOT EXISTS vitamin_c_min INTEGER DEFAULT 75,
ADD COLUMN IF NOT EXISTS vitamin_c_max INTEGER DEFAULT 90,
ADD COLUMN IF NOT EXISTS calcium_min INTEGER DEFAULT 1000,
ADD COLUMN IF NOT EXISTS calcium_max INTEGER DEFAULT 1300,
ADD COLUMN IF NOT EXISTS magnesium_min INTEGER DEFAULT 310,
ADD COLUMN IF NOT EXISTS magnesium_max INTEGER DEFAULT 420,
ADD COLUMN IF NOT EXISTS fiber_min INTEGER DEFAULT 25,
ADD COLUMN IF NOT EXISTS fiber_max INTEGER DEFAULT 38,
ADD COLUMN IF NOT EXISTS salt_min INTEGER DEFAULT 1500,
ADD COLUMN IF NOT EXISTS salt_max INTEGER DEFAULT 2300;
